@startuml
skinparam backgroundColor #EEF2F5
skinparam participantBackgroundColor #A9C2C3
skinparam participantBorderColor gray
skinparam sequenceLifeLineBackgroundColor #CC3333
skinparam sequenceArrowColor black
skinparam noteBackgroundColor #FDE284
skinparam noteBorderColor #FDE284

note left of server: delete coworkingspace: delete

participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as router
participant "<<middleware>>\n:auth" as auth
participant "<<controllers>>\n:coworkingspaces" as controller
participant "<<model>>\n:Coworkingspace" as modelSpace
participant "<<model>>\n:Reservation" as modelRes
participant "<<MongoDB>>\n:database" as db

-> server : req.delete('/api/v1/coworkingspaces/:id')
activate server

server -> router : app.use('/coworkingspaces', coworkingspaces)
activate router

router -> auth : protect, authorize
activate auth
auth --> router : next()
deactivate auth

router -> controller : deleteCoworkingspace
activate controller

controller -> modelSpace : findById(req.params.id)
activate modelSpace
modelSpace -> db : findById()
activate db
db --> modelSpace : coworkingspace
deactivate db
modelSpace --> controller : coworkingspace
deactivate modelSpace

controller -> modelRes : deleteMany({coworkingspace: req.params.id})
activate modelRes
modelRes -> db : remove()
activate db
db --> modelRes : success
deactivate db
modelRes --> controller : success
deactivate modelRes

controller -> modelSpace : coworkingspace.deleteOne()
activate modelSpace
modelSpace -> db : remove()
activate db
db --> modelSpace : success
deactivate db
modelSpace --> controller : success
deactivate modelSpace

<-- controller : response
deactivate controller
deactivate router
deactivate server
@enduml