@startuml
skinparam backgroundColor #EEF2F5
skinparam participantBackgroundColor #A9C2C3
skinparam participantBorderColor gray
skinparam sequenceLifeLineBackgroundColor #CC3333
skinparam sequenceArrowColor black
skinparam noteBackgroundColor #FDE284
skinparam noteBorderColor #FDE284

note left of server: get reservations: get

participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as router
participant "<<middleware>>\n:auth" as auth
participant "<<controllers>>\n:reservations" as controller
participant "<<model>>\n:Reservation" as model
participant "<<MongoDB>>\n:reservations" as db

-> server : req.get('/api/v1/reservations')
activate server

server -> router : app.use('/reservations', reservations)
activate router

router -> auth : protect
activate auth
auth --> router : next()
deactivate auth

router -> controller : getReservations
activate controller

controller -> model : find(filter).populate()
activate model

model -> db : find()
activate db
db --> model : reservations list
deactivate db

model --> controller : reservations list
deactivate model

<-- controller : response
deactivate controller
deactivate router
deactivate server
@enduml